Вторая попытка пропихнуть расширенные магазины для т21 и т25
SpacelessBay/TerraGov-Marine-Corps pull request #28
Opened 2023-01-03 13:19 UTC by siegluck

<!## About The Pull Request

Теперь в карго за 200 очков можно заказать один расширенный магазин для T25, вмещающий 120 патрон.
Теперь в карго... 350 очков... семь расширенных магазинов для T21, вмещающих по 50 патрон каждый.
Теперь в оружейном вендоре лежит 9 расширенных магазинов для Т21, вмещающих по 50 патрон каждый.
Спрайты красивые, сам делал.

## Why It's Good For The Game

- Морпехи будут покупать бесполезные вещи вместо B18
- Иногда, играя с Т21, я буду перезаряжаться не каждые пять секунд, а каждые семь
- Кто-то спиздит все магазины, добавится детективный геймплей с поиском этого кого-то
- Я их добавил в Вальгаллу в бесконечном количестве
- Даже в оружейном автомате на краше есть, я это учёл
- Ещё несколько магазинов цвета Браво
- Очередной ксенобафф
- Чистый код, мало лаг, много веселье, счастливый морпех, счастливый ксеноморф, жить хорошо, жить дружно, смотреть жёлтый магазин

:cl:
add: t25 ext mag
add: t21 ext mag
/:cl:

2023-01-04 15:03 UTC, Waselon commented
Т25 хороша сама по себе, хочешь большой магазин - бери Т29

2023-01-08 01:13 UTC, Blundir requested changes

2023-01-08 01:13 UTC, Blundir commented on lostbay/code/RU_items.dm
> +	containertype = /obj/structure/closet/crate/weapon
```suggestion
	containertype = /obj/structure/closet/crate/ammo
```

2023-01-08 01:13 UTC, Blundir commented on lostbay/code/RU_items.dm
> +	containertype = /obj/structure/closet/crate/weapon
```suggestion
	containertype = /obj/structure/closet/crate/ammo
```

2023-01-10 17:07 UTC, closed without merging